// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function E停止播放() {
  return window['go']['main']['App']['E停止播放']();
}

export function E投递视频文件(arg1, arg2, arg3) {
  return window['go']['main']['App']['E投递视频文件'](arg1, arg2, arg3);
}

export function E暂停播放() {
  return window['go']['main']['App']['E暂停播放']();
}

export function E获取系统时间() {
  return window['go']['main']['App']['E获取系统时间']();
}

export function E获取设备列表() {
  return window['go']['main']['App']['E获取设备列表']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}
