// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function E停止播放():Promise<string>;

export function E投递视频文件(arg1:string,arg2:string,arg3:string):Promise<string>;

export function E暂停播放():Promise<string>;

export function E获取系统时间():Promise<string>;

export function E获取设备列表():Promise<string>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenFileDialog():Promise<string>;
